nzb:
  hosts:
    nzb.snyderfamily.int
  
radarr:
  hosts:
    radarr.snyderfamily.int

sonarr:
  hosts:
    sonarr.snyderfamily.int

plex:
  hosts:
    plex.snyderfamily.int

dns:
  hosts:
    ns01.snyderfamily.int
    ns02.snyderfamily.int

directory:
  hosts:
    idm.snyderfamily.int

awx:
  ansible_connection: local
  hosts:
    localhost

media:
  children:
    nzb:
    radarr:
    sonarr:
    plex:

base:
  children:
    media:
    dns:
    directory:
    awx:
