---
- hosts: all
  roles:
    - base

- hosts: plex
  roles:
    - plex

- hosts: sonarr
  roles:
    - sonarr

- hosts: nzb
  roles:
    - nzb

- hosts: radarr
  roles:
    - radarr
    
- hosts: tautulli
  roles:
    - tautulli

- hosts: transmission
  roles:
    - transmission