---
- hosts: all
  roles:
    - base

- hosts: media
  tasks:
    - name: Create Media Group
      group:
        name: media
        gid: 3000
        state: present
        system: yes

- hosts: plex
  roles:
    - plex

- hosts: sonarr
  roles:
    - sonarr

- hosts: nzb
  roles:
    - nzb

- hosts: radarr
  roles:
    - radarr
    
- hosts: tautulli
  roles:
    - tautulli
