nzb:
  hosts:
    nzb.snyderfamily.int
  
radarr:
  hosts:
    radarr.snyderfamily.int

sonarr:
  hosts:
    sonarr.snyderfamily.int

plex:
  hosts:
    plex.snyderfamily.int

tautulli:
  hosts:
    tautulli.snyderfamily.int

transmission:
  hosts:
    transmission.snyderfamily.int

#dns:
#  hosts:
#    ns01.snyderfamily.int
#    ns02.snyderfamily.int
#
#directory:
#  hosts:
#    idm.snyderfamily.int

awx:
  hosts:
    awx.snyderfamily.int

media:
  children:
    nzb:
    radarr:
    sonarr:
    plex:
    tautulli:
    transmission:

