nzb:
  hosts:
    sabnzb.int.snyderfamily.co
  
sonarr:
  hosts:
    sonarr.int.snyderfamily.co

plex:
  hosts:
    plex.int.snyderfamily.co

tautulli:
  hosts:
    tautulli.int.snyderfamily.co

transmission:
  hosts:
    transmission.int.snyderfamily.co

jackett:
  hosts:
    jackett.int.snyderfamily.co

#dns:
#  hosts:
#    ns01.int.snyderfamily.co
#    ns02.int.snyderfamily.co
#
#directory:
#  hosts:
#    idm.int.snyderfamily.co

awx:
  hosts:
    127.0.0.1
