#!/bin/bash
#.bashrc

export PS1="\n[ User: \u ]\n[ Host: \h ($(ip a | grep 'ens' -A3 | grep -E 'inet.*10' | awk '{print $2}' | sed 's/\/24$//g')) ]\n[ You're in (( \w )) ]\n\n--> "
export HISTSIZE=10000
export HISTFILESIZE=10000
export EDITOR='/bin/vi'
export TERM='linux'
export INPUTRC=/etc/inputrc
export DMALLOC_OPTIONS=debug=0x34f47d83,inter=100,log=logfile
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# User Aliases
alias ll="ls -alh --color=auto"
alias ls="ls -alh --color=auto"
alias grep="grep --color=auto"

# Git Export
if rpm -q git
    then
        export GIT_SSH_COMMAND="ssh -i ~/.ssh/ctc_ed25519"
fi
