#!/bin/bash
#.bashrc

function GetIP(){
    ip a | grep -Ei 'inet\ 10\.' | awk '{print $2}' | sed -r 's/\/[0-9]{1,2}//g' | tr '\n' ',' | sed 's/,/, /g' | sed 's/, $//g'
}

export PS1="\n[ User: \u ]\n[ Host: \h ($(GetIP)) ]\n[ You're in (( \w )) ]\n\n--> "
export HISTSIZE=10000
export HISTFILESIZE=10000
export EDITOR='/bin/vi'
export TERM='linux'
export INPUTRC=/etc/inputrc
export DMALLOC_OPTIONS=debug=0x34f47d83,inter=100,log=logfile
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export LC_CTYPE=en_US.UTF-8

# Git Export
if rpm -q git >/dev/null 2>&1
    then
        if [[ -f ~/.ssh/ctc_ed25519 ]]
            then
                export GIT_SSH_COMMAND="ssh -i ~/.ssh/ctc_ed25519"
        fi
fi

# User Aliases
alias ll="ls -alh --color=auto"
alias ls="ls -alh --color=auto"
alias grep="grep --color=auto"

# Change to the working directory
if rpm -q ansible >/dev/null 2>&1
    then
        if [[ -d ~/.ansible ]]
            then
                cd ~/.ansible || echo 'Could not change to ANSIBLE working directory'
        fi
fi
