---
- name: Set a hostname
  hostname:
    name: sonarr

- name: Setup /etc/hosts file
  ansible.posix.synchronize:
    checksum: yes
    src: hosts
    dest: /etc/hosts
    owner: yes
    group: yes

- name: Create Media Group on all Media Servers
  group:
    name: media
    gid: 3000
    state: present
    system: yes

- name: Create OPT APPS directory on all Media Servers
  file:
    path: /opt/apps
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create the sonarr user
  user:
    name: sonarr
    home: /opt/apps/sonarr
    create_home: yes
    move_home: yes
    password: "$6$13EsWp/t8Y4T0/xH$m2I7DWDjcodxFTHAZIad1lZSers0XREz1dHkHzckd5TLPxJ5Wipv32gD4236M2BSIc.SE/.6kEc89fyEj/e.00"
    group: media
    state: present

- name: Create OPT APPS MEDIA directory
  file:
    path: /opt/apps/media
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Create OPT APPS APPDATA directory
  file:
    path: /opt/apps/sonarr/.appdata/
    state: directory
    group: media
    owner: sonarr
    mode: '770'

- name: Create OPT APPS NZBAPPDATA directory on all Media Servers
  file:
    path: /opt/apps/nzb_appdata
    state: directory
    group: media
    owner: root
    mode: '770'

- name: Mount NFS location on all Media Servers
  ansible.posix.mount:
    src: wickednas.snyderfamily.int:/plex
    path: /opt/apps/media
    fstype: nfs
    opts: defaults,rw
    state: mounted

- name: Mount NFS location on all Media Servers
  ansible.posix.mount:
    src: wickednas.snyderfamily.int:/nzb_appdata
    path: /opt/apps/nzb_appdata
    fstype: nfs
    opts: defaults,rw
    state: mounted

# Install the application
- name: Import GPG Key
  rpm_key:
    key: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
    state: present

- name: Import the Mono Repo
  yum_repository:
    name: "mono-centos8-stable"
    description: "Mono Project Linux Repository"
    baseurl: "https://download.mono-project.com/repo/centos8-stable/"
    enabled: yes
    gpgkey: "https://download.mono-project.com/repo/xamarin.gpg"
    gpgcheck: yes
    keepcache: "0"
    metadata_expire: "1"

- name: Import Sonarr Required Utilities
  vars:
    sonarr_tools:
      - wget
      - git
      - par2cmdline
      - p7zip
      - unrar
      - unzip
      - tar
      - gcc
      - python3-feedparser
      - python3-configobj
      - python3-cheetah
      - python3-dbus
      - python3-devel
      - libxslt-devel
      - yum-utils
      - mediainfo
      - libzen
      - libmediainfo
      - curl
      - gettext
      - mono-core
      - mono-devel
      - sqlite
  dnf:
    name: "{{ sonarr_tools }}"
    state: latest
    update_cache: yes

- name: Get Sonarr Sources
  get_url:
    url: https://services.sonarr.tv/v1/download/phantom-develop/latest?version=3&os=linux
    dest: /opt/apps/sonarr/sonarr.tar.gz

- name: Unarchive Sonarr Sources
  unarchive:
    remote_src: yes
    src: /opt/apps/sonarr/sonarr.tar.gz
    dest: /opt/apps/sonarr/.appdata/

- name: Move folder
  stat:
    path: /opt/apps/sonarr/.appdata/Sonarr
  register: virginpath

- name: Rename Sonarr to bin
  command:
    cmd: mv /opt/apps/sonarr/.appdata/Sonarr /opt/apps/sonarr/.appdata/bin
  when: virginpath.stat.exists

- name: Remove TAR archive
  file:
    name: /opt/apps/sonarr/sonarr.tar.gz
    state: absent

- name: Update Ownership and Permissions
  file:
    path: /opt/apps/sonarr/
    owner: sonarr
    group: media
    mode: '0770'
    recurse: yes

- name: Copy systemd service file
  ansible.posix.synchronize:
    checksum: yes
    src: sonarr.service
    dest: /etc/systemd/system/sonarr.service
    owner: yes
    group: yes
  register: systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd.changed

- name: Enable and Start Sonarr
  systemd:
    name: sonarr
    enabled: yes
    state: started

